#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100.
#Requirements:
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format

#for all the integer betwen 1-100
for i in $(seq 1 100);
do
    #if the integer when divided by 15 3 and 5 then the modulo is 0 
    if [ $((i % 15)) -eq 0 ];
    then
	echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ];
    then
	echo "Fizz"
    elif [ $((i % 5)) -eq 0 ];
    then
	echo "Buzz"
    else
	echo "$i"
    fi
done

	
