#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line with while and if
ADD=1
while [ "$ADD" -le 10 ];
do
    echo "Best School"
    if [ "$ADD" -eq 9 ]
    then
	echo "Hi"
    fi
    ((ADD=ADD+1))
done

