#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and with while
#displays 4 and then bad luck from China for the 4th loop iteration with case in
#displays 9 and then bad luck from Japan for the 9th loop iteration with case in
#displays 17 and then bad luck from Italy for the 17th loop iteration with case in

ADD=1
while [ "$ADD" -le 20 ];
do
    echo "$ADD"
    case "$ADD"
    in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
esac
	   (( ADD=ADD+1 ))
done
	   
	   
